apiVersion: apps/v1
kind: Deployment
metadata:
  name: hmcts-complaints-formbuilder-adapter-api-{{ .Values.environmentName }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hmcts-complaints-formbuilder-adapter
  template:
    metadata:
      labels:
        app: hmcts-complaints-formbuilder-adapter
        appGroup: hmcts-complaints-formbuilder-adapter
    spec:
      containers:
      - name: hmcts-complaints-formbuilder-adapter
        image: "754256621582.dkr.ecr.eu-west-2.amazonaws.com/formbuilder/hmcts-complaints-formbuilder-adapter-api:{{ .Values.circleSha1 }}"
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
        env:
        - name: HOST
          value: hmcts-complaints-formbuilder-adapter-{{ .Values.environmentName }}.apps.live-1.cloud-platform.service.justice.gov.uk
        - name: RAILS_LOG_TO_STDOUT
          value: "true"
        - name: OPTICS_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: hmcts-complaints-formbuilder-adapter-secrets-{{ .Values.environmentName }}
              key: optics_endpoint
        - name: SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: hmcts-complaints-formbuilder-adapter-secrets-{{ .Values.environmentName }}
              key: secret_key_base
        - name: JWE_SHARED_KEY
          valueFrom:
            secretKeyRef:
              name: hmcts-complaints-formbuilder-adapter-secrets-{{ .Values.environmentName }}
              key: jwe_shared_key
        - name: OPTICS_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: hmcts-complaints-formbuilder-adapter-secrets-{{ .Values.environmentName }}
              key: optics_secret_key
        - name: OPTICS_API_KEY
          valueFrom:
            secretKeyRef:
              name: hmcts-complaints-formbuilder-adapter-secrets-{{ .Values.environmentName }}
              key: optics_api_key
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: hmcts-complaints-formbuilder-adapter-secrets-{{ .Values.environmentName }}
              key: sentry_dsn
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: rds-instance-hmcts-complaints-adapter-{{ .Values.environmentName }}
              key: url
        - name: METRICS_AUTH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: hmcts-complaints-formbuilder-adapter-secrets-{{ .Values.environmentName }}
              key: metrics_auth_password
        - name: METRICS_AUTH_USERNAME
          valueFrom:
            secretKeyRef:
              name: hmcts-complaints-formbuilder-adapter-secrets-{{ .Values.environmentName }}
              key: metrics_auth_username
---
# workers
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hmcts-complaints-formbuilder-adapter-worker-{{ .Values.environmentName }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hmcts-complaints-formbuilder-adapter-worker
  template:
    metadata:
      labels:
        app: hmcts-complaints-formbuilder-adapter-worker
        appGroup: hmcts-complaints-formbuilder-adapter
    spec:
      containers:
      - name: hmcts-complaints-formbuilder-adapter
        image: "754256621582.dkr.ecr.eu-west-2.amazonaws.com/formbuilder/hmcts-complaints-formbuilder-adapter-worker:{{ .Values.circleSha1 }}"
        imagePullPolicy: Always
        env:
        - name: HOST
          value: hmcts-complaints-formbuilder-adapter-{{ .Values.environmentName }}.apps.live-1.cloud-platform.service.justice.gov.uk
        - name: RAILS_LOG_TO_STDOUT
          value: "true"
        - name: OPTICS_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: hmcts-complaints-formbuilder-adapter-secrets-{{ .Values.environmentName }}
              key: optics_endpoint
        - name: SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: hmcts-complaints-formbuilder-adapter-secrets-{{ .Values.environmentName }}
              key: secret_key_base
        - name: JWE_SHARED_KEY
          valueFrom:
            secretKeyRef:
              name: hmcts-complaints-formbuilder-adapter-secrets-{{ .Values.environmentName }}
              key: jwe_shared_key
        - name: OPTICS_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: hmcts-complaints-formbuilder-adapter-secrets-{{ .Values.environmentName }}
              key: optics_secret_key
        - name: OPTICS_API_KEY
          valueFrom:
            secretKeyRef:
              name: hmcts-complaints-formbuilder-adapter-secrets-{{ .Values.environmentName }}
              key: optics_api_key
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: hmcts-complaints-formbuilder-adapter-secrets-{{ .Values.environmentName }}
              key: sentry_dsn
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: rds-instance-hmcts-complaints-adapter-{{ .Values.environmentName }}
              key: url
        - name: METRICS_AUTH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: hmcts-complaints-formbuilder-adapter-secrets-{{ .Values.environmentName }}
              key: metrics_auth_password
        - name: METRICS_AUTH_USERNAME
          valueFrom:
            secretKeyRef:
              name: hmcts-complaints-formbuilder-adapter-secrets-{{ .Values.environmentName }}
              key: metrics_auth_username
