version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.7.0

jobs:
  test:
    working_directory: ~/circle
    docker:
      - image: circleci/buildpack-deps:14.04
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: lint
          command: docker-compose run --rm app bundle exec rubocop
      - run:
          name: test
          command: docker-compose run --rm app bundle exec rspec
  deploy_staging:
    working_directory: ~/circle/git/hmcts-complaints-formbuilder-adapter
    docker: &ecr_base_image
      - image: $AWS_BUILD_IMAGE_ECR_ACCOUNT_URL
        aws_auth:
          aws_access_key_id: $AWS_BUILD_IMAGE_ACCESS_KEY_ID
          aws_secret_access_key: $AWS_BUILD_IMAGE_SECRET_ACCESS_KEY
    steps:
      - checkout
      - setup_remote_docker
      - add_ssh_keys:
          fingerprints:
            - "7e:e7:44:be:a1:4b:4e:3c:56:65:3a:94:19:50:02:cc"
      - run:
          name: Setup base environment variable
          command: |
            echo "export BUILD_SHA=$CIRCLE_SHA1" >> $BASH_ENV
            echo "export SSH_FILE_FOR_SECRETS=~/.ssh/id_rsa_7ee744bea14b4e3c56653a94195002cc" >> $BASH_ENV
      - run:
          name: cloning deploy scripts
          command: 'git clone git@github.com:ministryofjustice/fb-deploy.git deploy-scripts'
      - run:
          name: build and push docker images
          environment:
            ENVIRONMENT_NAME: staging
          command: './deploy-scripts/bin/build'
      - run:
          name: deploy to staging
          environment:
            APPLICATION_NAME: hmcts-complaints-formbuilder-adapter
            PLATFORM_ENV: staging
            K8S_NAMESPACE: hmcts-complaints-formbuilder-adapter-staging
          command: './deploy-scripts/bin/deploy'

  deploy_production:
    working_directory: ~/circle/git/hmcts-complaints-formbuilder-adapter
    docker: *ecr_base_image
    steps:
      - checkout
      - setup_remote_docker
      - add_ssh_keys:
          fingerprints:
            - "7e:e7:44:be:a1:4b:4e:3c:56:65:3a:94:19:50:02:cc"
      - run:
          name: Setup base environment variable
          command: |
            echo "export BUILD_SHA=$CIRCLE_SHA1" >> $BASH_ENV
            echo "export SSH_FILE_FOR_SECRETS=~/.ssh/id_rsa_7ee744bea14b4e3c56653a94195002cc" >> $BASH_ENV
      - run:
          name: cloning deploy scripts
          command: 'git clone git@github.com:ministryofjustice/fb-deploy.git deploy-scripts'
      - run:
          name: build and push docker images
          environment:
            ENVIRONMENT_NAME: production
          command: './deploy-scripts/bin/build'
      - run:
          name: deploy to production
          environment:
            APPLICATION_NAME: hmcts-complaints-formbuilder-adapter
            PLATFORM_ENV: production
            K8S_NAMESPACE: hmcts-complaints-formbuilder-adapter-production
          command: './deploy-scripts/bin/deploy'

workflows:
  version: 2
  release:
    jobs:
      - test
      - deploy_staging:
          requires:
            - test
          filters:
            branches:
              only:
                - master
                - deploy-to-staging
      - confirm_production_deploy:
          type: approval
          requires:
            - deploy_staging
          filters:
            branches:
              only: master
      - deploy_production:
          requires:
            - confirm_production_deploy
          filters:
            branches:
              only: master
