version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@0.0.2
jobs:
  test:
    docker:
      - image: asmega/fb-builder:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: lint
          command: docker-compose run --rm app rubocop
      - run:
          name: test
          command: docker-compose run --rm app rspec
  deploy_staging:
    docker:
      - image: asmega/fb-builder:latest
    steps:
      - checkout
      - run:
          name: deploy to staging
          command: './deploy/scripts/circle_deploy.sh staging $KUBE_TOKEN_STAGING'

  deploy_production:
    docker:
      - image: asmega/fb-builder:latest
    steps:
      - checkout
      - run:
          name: deploy to production
          command: './deploy/scripts/circle_deploy.sh production $KUBE_TOKEN_PRODUCTION'

workflows:
  version: 2
  release:
    jobs:
      - test
      - aws-ecr/build_and_push_image:
          account-url: "754256621582.dkr.ecr.eu-west-2.amazonaws.com"
          repo: "form-builder/hmcts-complaints-formbuilder-adapter"
          region: ${AWS_DEFAULT_REGION}
          tag: "${CIRCLE_SHA1}"
          filters:
            branches:
              only: master
      - deploy_staging:
          requires:
            - aws-ecr/build_and_push_image
            - test
          filters:
            branches:
              only: master
      - confirm_production_deploy:
          type: approval
          requires:
            - deploy_staging
          filters:
            branches:
              only: master
      - deploy_production:
          requires:
            - confirm_production_deploy
          filters:
            branches:
              only: master
