version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.3.0

jobs:
  test:
    working_directory: ~/circle
    docker:
      - image: asmega/fb-builder:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: lint
          command: docker-compose run --rm app rubocop
      - run:
          name: test
          command: docker-compose run --rm app rspec
  deploy_staging:
    working_directory: ~/circle/git/hmcts-complaints-formbuilder-adapter
    docker:
      - image: asmega/fb-builder:latest
    steps:
      - checkout
      - setup_remote_docker
      - add_ssh_keys:
          fingerprints:
            - "7e:e7:44:be:a1:4b:4e:3c:56:65:3a:94:19:50:02:cc"
      - run:
          name: deploy to staging
          command: './deploy/scripts/circle_deploy.sh "APP_${CIRCLE_SHA1}" staging $KUBE_TOKEN_STAGING'

  deploy_production:
    working_directory: ~/circle/git/hmcts-complaints-formbuilder-adapter
    docker:
      - image: asmega/fb-builder:latest
    steps:
      - checkout
      - setup_remote_docker
      - add_ssh_keys:
          fingerprints:
            - "7e:e7:44:be:a1:4b:4e:3c:56:65:3a:94:19:50:02:cc"
      - run:
          name: deploy to production
          command: './deploy/scripts/circle_deploy.sh "APP_${CIRCLE_SHA1}" production $KUBE_TOKEN_PRODUCTION'

workflows:
  version: 2
  release:
    jobs:
      - test
      - aws-ecr/build-and-push-image:
          name: push_app_image
          dockerfile: Dockerfile
          account-url: AWS_ECR_ACCOUNT_URL
          region: AWS_DEFAULT_REGION
          repo: "form-builder/hmcts-complaints-formbuilder-adapter"
          tag: "APP_${CIRCLE_SHA1}"
          filters:
            branches:
              only: master
      - aws-ecr/build-and-push-image:
          name: push_worker_image
          dockerfile: Dockerfile.worker
          account-url: AWS_ECR_ACCOUNT_URL
          region: AWS_DEFAULT_REGION
          repo: "form-builder/hmcts-complaints-formbuilder-adapter"
          tag: "WORKER_${CIRCLE_SHA1}"
          filters:
            branches:
              only: master
      - deploy_staging:
          requires:
            - push_app_image
            - push_worker_image
            - test
          filters:
            branches:
              only: master
      - confirm_production_deploy:
          type: approval
          requires:
            - deploy_staging
          filters:
            branches:
              only: master
      - deploy_production:
          requires:
            - confirm_production_deploy
          filters:
            branches:
              only: master
