version: 1

update_configs:
  - package_manager: "ruby:bundler"
    directory: "/"
    update_schedule: "live"
    default_reviewers:
    - asmega
  - package_manager: "docker"
    directory: "/"
    update_schedule: "daily"
    default_reviewers:
    - asmega
